service: invoice-service

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment: ${file(./serverless.env.yml):${opt:stage}}

package:
  exclude:
    - ./test/**

functions:

  createInvoice:
    handler: handlers/invoices.create
    events:
      - http:
          path: invoice
          method: post
          cors: true
  createClient:
    handler: handlers/clients.create
    events:
      - http:
          path: client
          method: post
          cors: true
  createPayment:
    handler: handlers/payments.create
    events:
      - http:
          path: payment
          method: post
          cors: true

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2017"]