service: invoice-service

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment: ${file(./serverless.env.yml):${opt:stage}}

package:
  exclude:
    - ./test/**

functions:

  invoices-create:
    handler: handlers/invoices.create
    events:
      - http:
          path: invoice
          method: post
          cors: true
  invoices-get-all:
    handler: handlers/invoices.getAll
    events:
      - http:
          path: invoices
          method: get
          cors: true
  clients-create:
    handler: handlers/clients.create
    events:
      - http:
          path: client
          method: post
          cors: true
  clients-get-all:
    handler: handlers/clients.getAll
    events:
      - http:
          path: clients
          method: get
          cors: true
  payments-create:
    handler: handlers/payments.create
    events:
      - http:
          path: payment
          method: post
          cors: true
  payments-get-all:
    handler: handlers/payments.getAll
    events:
      - http:
          path: payments
          method: get
          cors: true

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2017"]